### PR TITLE
fix the package name to enable `import safe_asar`

### PR DESCRIPTION
**Pull request by agrouaze**
align the lib structure with existing SAR xarray readers developped by UMR-LOPS:
 - xarray-ceos-alos
 - xarray-safe-rcm
 - xarray-safe-s1

### CODE REVIEW

**Comment by agrouaze** [comment]
I suggest to to this change before anything else, sothat users can do:
```python

import safe_asar
# and once the PR1 will be merged
from safe_asar.asa_wvi_1p_reader import ASA_WVI_1P_Reader
```

**Comment by rmarquarlops** [comment]
I wonder if we should also keep the name xarray-safe-asar as the asar data is stored in .N1 files and not safe repertories. Maybe it should be xarray-n1-asar ?

**Review by rmarquarlops — COMMENTED** [review]
As I commented, maybe safe_asar is not the best name as we are not dealing with safe data ?

**Comment by agrouaze** [comment]
@rmarquarlops I rename the lib (not the repository) `safe_asar` -> `n1_asar`.

**Review by rmarquarlops — APPROVED** [review]

**Pull request merged**
